import processSketches from "@/assets/process-sketches.webp";
import brandApps from "@/assets/brand-applications.webp";

export type Project = {
  slug: string;
  n: string;
  title: string;
  tag: string;
  cat: "Brand Identity" | "Logo & Packaging" | "Digital";
  image: string;
  heroBanner?: string;
  wordmarkImage?: string;
  processImage?: string;
  logoImage: string;
  alt: string;
  client: string;
  location?: string;
  liveUrl?: string;
  status?: string;
  role: string;
  duration: string;
  services: string[];
  headline: string;
  summary: string;
  challenge: string;
  insight: string;
  process: { t: string; d: string }[];
  palette: { name: string; hex: string }[];
  type: { display: string; body: string };
  results: { k: string; v: string }[];
  quote: { text: string; who: string };
  gallery: { src: string; alt: string }[];
};

const brandRole = "Brand Strategist & Identity Designer";
const brandServices = ["Brand Strategy", "Logo Design", "Visual Identity", "Brand Applications"];
const brandProcess = [
  { t: "Discover", d: "Kick-off conversation to understand the business, audience and ambitions behind the brand." },
  { t: "Define", d: "Positioning and creative direction agreed before a single mark is drawn." },
  { t: "Design", d: "Logo concepts explored by hand, refined into a distinctive, ownable identity." },
  { t: "Deliver", d: "A complete identity kit — logos, colour, type and applications, ready to use." },
];

export const projects: Project[] = [
  {
    slug: "pelican-social-bar-and-grill",
    processImage: `${import.meta.env.BASE_URL}assets/pelicansocial_process.webp`,
    wordmarkImage: `${import.meta.env.BASE_URL}assets/pelicansocial_wordmark.svg`,
    heroBanner: `${import.meta.env.BASE_URL}assets/pelicansocial_casestudybanner.webp`,
    n: "01",
    title: "Pelican Social Bar & Grill",
    tag: "Identity • Brand Strategy",
    cat: "Brand Identity",
    image: `${import.meta.env.BASE_URL}assets/pelicansocial_thumbnail.webp`,
    logoImage: `${import.meta.env.BASE_URL}assets/pelicansocial_logo.webp`,
    alt: "Pelican Social Bar and Grill brand identity",
    client: "Pelican Social",
    location: "Simpson Bay, Sint Maarten (Caribbean)",
    liveUrl: "https://pelicansocialsxm.com/",
    status: "Live",
    role: brandRole,
    duration: "4 Weeks",
    services: brandServices,
    headline: "Boho-chic brand identity for a Caribbean seaside bar & grill.",
    summary: "A complete brand and logo identity for Pelican Social — a vibrant resort-side sports bar and grill in Simpson Bay, Sint Maarten.",
    challenge: "Standing out in a competitive Caribbean tourism market surrounded by time-share resorts and Airbnb travelers, requiring a brand that feels welcoming after dark, distinct on the strip, and authentic to island hospitality.",
    insight: "Modern Caribbean hospitality thrives when it balances effortless beach-side relaxation with artisanal culinary care. The brand system highlights scratch-made quality within a laid-back boho-chic aesthetic.",
    process: brandProcess,
    palette: [
      { name: "Pelican Navy", hex: "#09414A" },
      { name: "Ocean Teal", hex: "#15636F" },
      { name: "Seaside Turquoise", hex: "#37B0B5" },
      { name: "Sunset Coral", hex: "#EF806A" },
      { name: "Caribbean Sand", hex: "#EFC18E" },
    ],
    type: { display: "Syne ExtraBold", body: "Inter Regular" },
    results: [
      { k: "100%", v: "Scratch Brand System" },
      { k: "SXM", v: "Simpson Bay Landmark" },
      { k: "Boho", v: "Chic Coastal Vibe" },
      { k: "✓", v: "Full Asset Delivery" },
    ],
    quote: { text: "The new identity perfectly captures our boho-chic Caribbean vibe and makes Pelican Social unmissable to resort guests and tourists.", who: "Management, Pelican Social SXM" },
    gallery: [
      { src: processSketches, alt: "Logo sketches and identity exploration" },
      { src: brandApps, alt: "Brand applications" },
    ],
  },
  {
    slug: "ikon-trailers",
    processImage: `${import.meta.env.BASE_URL}assets/ikontrailers_process.webp`,
    wordmarkImage: `${import.meta.env.BASE_URL}assets/ikontrailers_wordmark.svg`,
    heroBanner: `${import.meta.env.BASE_URL}assets/ikontrailers_herobanner.webp`,
    n: "02",
    title: "Ikon Trailers",
    tag: "Identity • Heavy Industrial",
    cat: "Brand Identity",
    image: `${import.meta.env.BASE_URL}assets/ikontrailerscom_thumbnail.webp`,
    logoImage: `${import.meta.env.BASE_URL}assets/ikontrailers_logo.webp`,
    alt: "Ikon Trailers brand identity",
    client: "IKON Trailers.com",
    location: "San Antonio, Texas (USA)",
    liveUrl: "https://ikontrailers.com/",
    status: "Live",
    role: brandRole,
    duration: "6 Weeks",
    services: brandServices,
    headline: "An iconic mark engineered for heavy-duty highway performance.",
    summary: "Brand identity and logo system for IKON Trailers.com — a San Antonio heavy-duty trailer dealer selling bottom dumps, end dumps, tankers, and flatbeds.",
    challenge: "Designing a high-impact mark that projects unshakeable industrial strength and premium dealer reliability across massive steel machinery, digital inventory, and fleet apparel.",
    insight: "In commercial heavy equipment, authority is built on scale, simplicity, and steel-clad confidence. The mark must read instantly at 70 mph on Texas highways and on digital buyer portals.",
    process: brandProcess,
    palette: [
      { name: "Ikon Red", hex: "#FE0000" },
      { name: "Industrial Black", hex: "#0E0E10" },
      { name: "Crimson Red", hex: "#FE4040" },
      { name: "Steel Silver", hex: "#8E9399" },
      { name: "Pure White", hex: "#FFFFFF" },
    ],
    type: { display: "Syne ExtraBold", body: "Inter Regular" },
    results: [
      { k: "70mph", v: "Highway Visibility" },
      { k: "TX", v: "San Antonio HQ" },
      { k: "Steel", v: "Heavy-Duty System" },
      { k: "✓", v: "Fleet & Print Ready" },
    ],
    quote: { text: "The IKON logo looks incredible on our heavy machinery and workwear. It gives our dealership the bold, iconic edge we needed.", who: "Founder, IKON Trailers" },
    gallery: [
      { src: processSketches, alt: "Logo sketches and identity exploration" },
      { src: brandApps, alt: "Brand applications" },
    ],
  },
  {
    slug: "iron-acre-land-co",
    processImage: `${import.meta.env.BASE_URL}assets/ironacrelandco_process.webp`,
    wordmarkImage: `${import.meta.env.BASE_URL}assets/ironacre_wordmark.svg`,
    heroBanner: `${import.meta.env.BASE_URL}assets/ironacrelandco_herobanner.webp`,
    n: "03",
    title: "Iron Acre Land Co",
    tag: "Identity • Excavation & Land",
    cat: "Brand Identity",
    image: `${import.meta.env.BASE_URL}assets/ironacreco_thumbnail.webp`,
    logoImage: `${import.meta.env.BASE_URL}assets/ironacrelandco_logo.webp`,
    alt: "Iron Acre Land Co brand identity",
    client: "Iron Acre Land Co",
    location: "United States",
    liveUrl: "https://www.ironacrelandco.com/",
    status: "Live",
    role: brandRole,
    duration: "4 Weeks",
    services: brandServices,
    headline: "Tough, no-nonsense visual identity forged for dirt and steel.",
    summary: "A rugged yet refined brand identity for Iron Acre Land Co — specializing in excavation, land management, and equine property development.",
    challenge: "Merging the raw power of iron and land into a simple, tough mark that scales seamlessly from heavy excavation machinery and truck decals to workwear hats and contractor branding.",
    insight: "Landowners and excavation contractors respect clarity and durability. A bold geometric emblem combining steel and earth creates immediate authority on job sites.",
    process: brandProcess,
    palette: [
      { name: "Iron Black", hex: "#040807" },
      { name: "Slate Steel", hex: "#434645" },
      { name: "Raw Silver", hex: "#C1C2C2" },
      { name: "Pure White", hex: "#FFFFFF" },
      { name: "Earth Bronze", hex: "#556B2F" },
    ],
    type: { display: "Syne ExtraBold", body: "Inter Regular" },
    results: [
      { k: "Dirt", v: "Excavation & Land" },
      { k: "Steel", v: "Heavy Machine Badge" },
      { k: "Apparel", v: "Embroidery Specs" },
      { k: "✓", v: "Brand Guidelines" },
    ],
    quote: { text: "Simple, tough, and commands respect on every job site. It looks phenomenal on the side of our trucks and heavy machinery.", who: "Owner, Iron Acre Land Co" },
    gallery: [
      { src: processSketches, alt: "Logo sketches and identity exploration" },
      { src: brandApps, alt: "Brand applications" },
    ],
  },
  {
    slug: "friends-of-unionville",
    processImage: `${import.meta.env.BASE_URL}assets/friendsofunionville_process.webp`,
    wordmarkImage: `${import.meta.env.BASE_URL}assets/friendsofunionville_wordmark.svg`,
    heroBanner: `${import.meta.env.BASE_URL}assets/friendsofunionville_herobanner.webp`,
    n: "04",
    title: "Friends of Unionville",
    tag: "Identity • Non-Profit",
    cat: "Brand Identity",
    image: `${import.meta.env.BASE_URL}assets/friendsofunionville_thumbnail.webp`,
    logoImage: `${import.meta.env.BASE_URL}assets/friendsofunionvillecolor_logo.webp`,
    alt: "Friends of Unionville brand identity",
    client: "Friends of Unionville",
    location: "Unionville, Pennsylvania (USA)",
    liveUrl: "https://www.friendsofunionville.org/",
    status: "Live",
    role: brandRole,
    duration: "5 Weeks",
    services: brandServices,
    headline: "A warm, community-centered identity for a historic village.",
    summary: "Visual identity and logo design for Friends of Unionville — a non-profit dedicated to preserving historic character and fostering vibrant community growth.",
    challenge: "Capturing the historic charm, scenic nature, and walkable crossroads heritage of Unionville, while intentionally avoiding blue to stand apart from nearby municipal organizations.",
    insight: "Unionville's identity was born at a historic crossroads. An organic green and crimson palette paired with warm typography highlights togetherness, scenic beauty, and local pride.",
    process: brandProcess,
    palette: [
      { name: "Crossroads Slate", hex: "#69899F" },
      { name: "Historic Brick", hex: "#AE461F" },
      { name: "Village Sun", hex: "#FCAD37" },
      { name: "Deep Forest", hex: "#163932" },
      { name: "Harvest Gold", hex: "#AA8A41" },
      { name: "Linen Sand", hex: "#E7E1D6" },
    ],
    type: { display: "Syne ExtraBold", body: "Inter Regular" },
    results: [
      { k: "Village", v: "Historic Preservation" },
      { k: "PA", v: "Unionville Community" },
      { k: "Organic", v: "Non-Blue Palette" },
      { k: "✓", v: "Community Asset Kit" },
    ],
    quote: { text: "The identity brings our village history to life. It feels warm, connected, and truly represents our vibrant community.", who: "Board Member, Friends of Unionville" },
    gallery: [
      { src: processSketches, alt: "Logo sketches and identity exploration" },
      { src: brandApps, alt: "Brand applications" },
    ],
  },
  {
    slug: "sound-curves",
    wordmarkImage: `${import.meta.env.BASE_URL}assets/soundcurves_wordmark.svg`,
    heroBanner: `${import.meta.env.BASE_URL}assets/soundcurves_herobanner.webp`,
    n: "05",
    title: "Sound Curves",
    tag: "UI/UX • Web Architecture",
    cat: "Digital",
    image: `${import.meta.env.BASE_URL}assets/soundcurves_thumbnail.webp`,
    logoImage: `${import.meta.env.BASE_URL}assets/soundcurves_website.webp`,
    alt: "Sound Curves website design",
    client: "SoundCurves",
    location: "Global",
    liveUrl: "",
    status: "In Development",
    role: "UI/UX Designer & Web Architect",
    duration: "6 Weeks",
    services: ["UX Design", "UI Design", "Information Architecture", "Figma Design System"],
    headline: "High-fidelity digital storefront for $799 audiophile earphones.",
    summary: "Website architecture and 5-page Figma interface design for SoundCurves — bridging high-end acoustic engineering with luxury consumer web design.",
    challenge: "Communicating the acoustic superiority of $799 premium earphones to both seasoned audiophiles and discerning consumers through an intuitive, immersive web hierarchy.",
    insight: "Sound curves are visual representations of acoustic precision. Dark mode elegance, fluid product showcases, and interactive tech specs justify premium value.",
    process: [
      { t: "Discover", d: "Understanding the audience, content and goals for the site." },
      { t: "Architect", d: "Sitemap and page structure mapped before any pixels." },
      { t: "Design", d: "High-fidelity screens with motion and interaction designed in." },
      { t: "Build", d: "Responsive front-end developed and shipped." },
    ],
    palette: [
      { name: "Acoustic Obsidian", hex: "#0C0D10" },
      { name: "Sonic Graphite", hex: "#22252C" },
      { name: "Audio Gold", hex: "#D4AF37" },
      { name: "Accent Lime", hex: "#A6FF00" },
    ],
    type: { display: "Syne Bold", body: "Inter Regular" },
    results: [
      { k: "5 Pages", v: "Desktop & Mobile Figma" },
      { k: "$799", v: "Audiophile Positioning" },
      { k: "High-Fi", v: "Interactive Architecture" },
      { k: "✓", v: "Dev-Ready Handoff" },
    ],
    quote: { text: "The design layout and page architecture hit the exact sweet spot between technical precision and premium luxury.", who: "Creative Director, SoundCurves" },
    gallery: [
      { src: processSketches, alt: "Wireframes and design exploration" },
      { src: brandApps, alt: "Website screens" },
    ],
  },
  {
    slug: "moods-n-meds",
    wordmarkImage: `${import.meta.env.BASE_URL}assets/moodnmeds_wordmark.svg`,
    heroBanner: `${import.meta.env.BASE_URL}assets/moodnmeds_herobanner.webp`,
    n: "06",
    title: "Moods n Meds",
    tag: "UI/UX • Health Tech",
    cat: "Digital",
    image: `${import.meta.env.BASE_URL}assets/moodnmeds_thumbnail.webp`,
    logoImage: `${import.meta.env.BASE_URL}assets/moodsnmeds_website.webp`,
    alt: "Moods n Meds website design",
    client: "Moods N Meds",
    location: "Digital App",
    liveUrl: "",
    status: "In Development",
    role: "UI/UX Designer & Web Architect",
    duration: "5 Weeks",
    services: ["UX Design", "UI Design", "Web App Prototype", "Information Architecture"],
    headline: "A serene web app interface designed for anxiety relief and daily calm.",
    summary: "UI/UX web app design for Moods N Meds — creating a tranquil digital environment with mood logging, Zen garden imagery, and medication reviews.",
    challenge: "Structuring complex medical directories, medication user reviews, and daily emotion logging into an interface that reduces anxiety rather than inducing visual overload.",
    insight: "Calming digital experiences require generous whitespace, serene Zen garden aesthetics, natural tones, and friction-free 3-button mood tracking.",
    process: [
      { t: "Discover", d: "Understanding the audience, content and goals for the site." },
      { t: "Architect", d: "Sitemap and page structure mapped before any pixels." },
      { t: "Design", d: "High-fidelity screens with motion and interaction designed in." },
      { t: "Build", d: "Responsive front-end developed and shipped." },
    ],
    palette: [
      { name: "Zen Slate", hex: "#2E3840" },
      { name: "Sage Calm", hex: "#88AB8E" },
      { name: "Lavender Mist", hex: "#E3E7F1" },
      { name: "Accent Lime", hex: "#A6FF00" },
    ],
    type: { display: "Syne Bold", body: "Inter Regular" },
    results: [
      { k: "Zen", v: "Calm Visual Vibe" },
      { k: "3-Tap", v: "Daily Mood Tracker" },
      { k: "Clean", v: "Medication Review UI" },
      { k: "✓", v: "Figma Component System" },
    ],
    quote: { text: "The calming vibe and Zen garden theme created a stress-free environment for our users. The mood log interaction is effortless.", who: "Product Owner, Moods N Meds" },
    gallery: [
      { src: processSketches, alt: "Wireframes and design exploration" },
      { src: brandApps, alt: "Website screens" },
    ],
  },
  {
    slug: "yellow-dot-energy",
    wordmarkImage: `${import.meta.env.BASE_URL}assets/yellowdot_wordmark.svg`,
    heroBanner: `${import.meta.env.BASE_URL}assets/yellowdot_herobanner.webp`,
    n: "07",
    title: "Yellow Dot Energy",
    tag: "UI/UX • Product Strategy",
    cat: "Digital",
    image: `${import.meta.env.BASE_URL}assets/yellowdot_thumbnail.webp`,
    logoImage: `${import.meta.env.BASE_URL}assets/yellowdot_app.webp`,
    alt: "Yellow Dot Energy mobile app design",
    client: "Yellow Dot Energy",
    location: "Nairobi, Kenya & Global",
    liveUrl: "https://www.yellowdotenergy.com/",
    status: "Live",
    role: "Product Strategy & UI/UX Designer",
    duration: "5 Weeks",
    services: ["Product Strategy", "UX Design", "UI Design", "Design System"],
    headline: "Connecting stakeholders across clean renewable energy solutions.",
    summary: "Digital platform and product interface for Yellow Dot Energy — empowering customers, investors, and vendors to connect over commercial solar installations.",
    challenge: "Simplifying complex solar PV system metrics, net-metering telemetry, and financing options into an accessible, high-converting digital platform.",
    insight: "Renewable energy adoption relies on transparent data. Glanceable energy audit visuals and streamlined solar vendor portals accelerate clean tech investments.",
    process: [
      { t: "Discover", d: "User research and a clear map of the core jobs-to-be-done." },
      { t: "Flows", d: "User journeys and wireframes for every key task." },
      { t: "Design", d: "A polished, accessible UI with a reusable component set." },
      { t: "Handoff", d: "Developer-ready specs and a living design system." },
    ],
    palette: [
      { name: "Solar Yellow", hex: "#FFD100" },
      { name: "Clean Tech Dark", hex: "#111625" },
      { name: "Grid Slate", hex: "#2C364C" },
      { name: "Accent Lime", hex: "#A6FF00" },
    ],
    type: { display: "Syne Bold", body: "Inter Regular" },
    results: [
      { k: "Solar PV", v: "Renewable Platform" },
      { k: "B2B", v: "Vendor & Investor Hub" },
      { k: "Audit", v: "Energy Efficiency UI" },
      { k: "✓", v: "Responsive App Launch" },
    ],
    quote: { text: "The web application bridges complex renewable energy metrics with seamless client experience. It makes solar power accessible.", who: "Executive Team, Yellow Dot Energy" },
    gallery: [
      { src: processSketches, alt: "App wireframes and flows" },
      { src: brandApps, alt: "App interface screens" },
    ],
  },
  {
    slug: "green-essentials-turf-and-mosquito",
    processImage: `${import.meta.env.BASE_URL}assets/greenessentials_process.webp`,
    wordmarkImage: `${import.meta.env.BASE_URL}assets/greenessentil_wordmark.svg`,
    heroBanner: `${import.meta.env.BASE_URL}assets/greenessentials_herobanner.webp`,
    n: "08",
    title: "Green Essentials Turf & Mosquito",
    tag: "Logo Design • Environmental",
    cat: "Logo & Packaging",
    image: `${import.meta.env.BASE_URL}assets/greenessentials_thumbnail.webp`,
    logoImage: `${import.meta.env.BASE_URL}assets/greenessentials_logo.webp`,
    alt: "Green Essentials Turf and Mosquito logo design",
    client: "Green Essentials Turf & Mosquito",
    location: "Loganville, Georgia (USA)",
    liveUrl: "https://www.greenessentials.info/",
    status: "Live",
    role: "Logo Designer",
    duration: "3 Weeks",
    services: ["Logo Design", "Mark Refinement", "File Delivery"],
    headline: "Dual-action logo identity for lawn fertilization and mosquito control.",
    summary: "Logo and brand identity for Green Essentials Turf & Mosquito — creating a sharp, dual-concept mark for lawn care and pest control services.",
    challenge: "Visually combining two distinct services — lush lawn fertilization and mosquito defense — into a unified, high-impact mark that pops on service vehicles and door hangers.",
    insight: "Blending botanical leaf geometry with protective shield symbolism creates a crisp, trustworthy mark representing both vibrant green turf and bug-free outdoor living.",
    process: [
      { t: "Discover", d: "Understanding the business, its customers and where the mark will live." },
      { t: "Sketch", d: "Concept directions explored by hand before refinement." },
      { t: "Refine", d: "The chosen direction polished into a versatile final mark." },
      { t: "Deliver", d: "Full file kit for print, vehicles and digital use." },
    ],
    palette: [
      { name: "Turf Dark Green", hex: "#193B28" },
      { name: "Lawn Leaf Green", hex: "#457342" },
      { name: "Mosquito Defense Blue", hex: "#1D324A" },
      { name: "Shield Soft Grey", hex: "#B3BBB6" },
      { name: "Canvas Off-White", hex: "#E6E5E5" },
    ],
    type: { display: "Syne ExtraBold", body: "Inter Regular" },
    results: [
      { k: "2-in-1", v: "Dual Service Icon" },
      { k: "GA", v: "Loganville Service Area" },
      { k: "Fleet", v: "Truck & Print Asset Kit" },
      { k: "✓", v: "Vector Master Files" },
    ],
    quote: { text: "The logo clearly communicates both of our main services — lawn treatments and mosquito control. It looks fantastic on our truck wrap!", who: "Owner, Green Essentials Lawn Service" },
    gallery: [
      { src: processSketches, alt: "Logo sketches and exploration" },
      { src: brandApps, alt: "Brand applications" },
    ],
  },
];

export const getProject = (slug: string) => projects.find((p) => p.slug === slug);
